# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee475b877a2f85fddcb221173a993b94d79e7e384a29094bca927bc7de831f655090e9b4854a4bd2fa08031a918ba7adf82a6962794c91e81fe72bc6e4b154b1

test:
  secret_key_base: 0ba9eb83e2396965521f1e12b0d6baa9847ff189020395328933490d1ef8f05cc4b60c5e3448472b2763d7c887dc9da7e4090db242c818dc89b96b3804416ef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
